# Generated by Django 5.2.8 on 2025-11-27 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
                ('ragas_score', models.FloatField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'digest_digest',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['-generated_at'], name='digest_dige_generat_0add93_idx'), models.Index(fields=['status'], name='digest_dige_status_e570b1_idx')],
            },
        ),
    ]
