# Generated by Django 5.2.8 on 2025-11-27 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('chunks_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'content_contentsource',
                'indexes': [models.Index(fields=['type'], name='content_con_type_ef7b3c_idx'), models.Index(fields=['status'], name='content_con_status_3dc034_idx')],
            },
        ),
    ]
