# Generated by Django 5.2.8 on 2025-11-27 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('progress', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_learningprogress',
                'indexes': [models.Index(fields=['topic'], name='learning_le_topic_6ac6a8_idx'), models.Index(fields=['-updated_at'], name='learning_le_updated_f6cc7d_idx')],
            },
        ),
    ]
