# Generated by Django 5.2.8 on 2025-11-27 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('fetch_interval', models.IntegerField(default=360)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rss_rssfeed',
                'indexes': [models.Index(fields=['feed_url'], name='rss_rssfeed_feed_ur_6a8d05_idx')],
            },
        ),
        migrations.CreateModel(
            name='RSSArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='rss.rssfeed')),
            ],
            options={
                'db_table': 'rss_rssarticle',
                'indexes': [models.Index(fields=['feed'], name='rss_rssarti_feed_id_d417d3_idx'), models.Index(fields=['url'], name='rss_rssarti_url_05f89b_idx'), models.Index(fields=['content_hash'], name='rss_rssarti_content_ab2e01_idx')],
            },
        ),
    ]
